title: Operatoren gebruiken om voorwaarden te controleren
hero_image: images/banner.png
description: Operatoren gebruiken om voorwaarden te controleren
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Operatoren gebruiken om voorwaarden te controleren
