title: scratch3-operators-conditions
hero_image: images/banner.png
description: scratch3-operators-conditions description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
