---
title: Defnyddio gweithredwyr i wirio amodau
hero_image: images/banner.png
description: Defnyddio gweithredwyr i wirio amodau
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Defnyddio gweithredwyr i wirio amodau
