title: Usando operadores para verificar condições
hero_image: images/banner.png
description: Usando operadores para verificar condições
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Usando operadores para verificar condições
