---
title: Použití operátorů ke kontrole podmínek
hero_image: images/banner.png
description: Použití operátorů ke kontrole podmínek
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Použití operátorů ke kontrole podmínek
