---
title: Utilizando operadores para comprobar las condiciones
hero_image: images/banner.png
description: Utilizando operadores para comprobar las condiciones
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Utilizando operadores para comprobar las condiciones
