---
title: Używanie operatorów do sprawdzania warunków
hero_image: images/banner.png
description: Używanie operatorów do sprawdzania warunków
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Używanie operatorów do sprawdzania warunków
