title: Using operators to check conditions
hero_image: images/banner.png
description: Using operators to check conditions
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Using operators to check conditions
