---
title: Utilisation des opérateurs pour vérifier les conditions
hero_image: images/banner.png
description: Utilisation des opérateurs pour vérifier les conditions
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Utilisation des opérateurs pour vérifier les conditions
