title: Usare gli operatori per verificare le condizioni
hero_image: images/banner.png
description: Usare gli operatori per verificare le condizioni
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Usare gli operatori per verificare le condizioni
